# JHY: NOTE: why choose canny? Since canny is almost the same as HED except for canny's GroundingDownsampler is learnable parameter, while HED just down sample.

diffusion:
  target: ldm.models.diffusion.ldm.LatentDiffusion
  params:
    linear_start: 0.00085
    linear_end: 0.012
    timesteps: 1000
   

model:
  target: ldm.modules.diffusionmodules.openaimodel.UNetModel
  params:
    image_size: 64 # unused in the unet, but will be used when create xT
    in_channels: 4
    out_channels: 4
    model_channels: 320
    attention_resolutions: [ 4, 2, 1 ]
    num_res_blocks: 2
    channel_mult: [ 1, 2, 4, 4 ]
    num_heads: 8
    transformer_depth: 1
    context_dim: 768
    fuser_type: gatedSA  #  gatedCA or gatedSA. We have ablate this, self-attention is better than cross-attention, thus please set this as gatedSA usually
    use_checkpoint: True


    # JHY: NOTE: need to modify
    grounding_downsampler:
      target: ldm.modules.diffusionmodules.canny_rgb_grounding_downsampler.GroundingDownsampler
      params:
        resize_input: 256
        out_dim: 8 
        hidden_dim: 4

    # JHY: NOTE: need to modify
    grounding_tokenizer:
      target: ldm.modules.diffusionmodules.canny_rotation_3d_grounding_net.PositionNet
      params:
        resize_input: 256
        out_dim: 768 
        pointcloud_encoder: "ULIP2_pointbert_embedding"


autoencoder:
  target: ldm.models.autoencoder.AutoencoderKL
  params:
    scale_factor: 0.18215 
    embed_dim: 4
    ddconfig:
      double_z: true
      z_channels: 4
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult:
      - 1
      - 2
      - 4
      - 4
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0


text_encoder:
  target: ldm.modules.encoders.modules.FrozenCLIPEmbedder



# JHY: NOTE: need to modify
train_dataset_names: 
  ULIP2ShapeNet:   # mainly this
    prob_use_caption: 0.6
    image_size: 512
    keyword: "chair"
    grounding_type: "canny"
    sample_angle_range: 60
    prob_use_3d_info: 0.9     # similar to classifier free guidance case
    pointcloud_encoder: "ULIP2_pointbert_embedding"


# JHY: NOTE: need to modify
grounding_tokenizer_input:
  target: grounding_input.canny_rotation_3d_grounding_tokinzer_input.GroundingNetInput


# JHY: NOTE: need to modify
grounding_downsampler_input:
  target: grounding_input.canny_grounding_downsampler_input.GroundingDSInput
